export default {
  临汾: {
    key: "lfs",
    name: "临汾",
    filePath: "lfs",
    registered: false,
  },
  永和县: {
    key: "yhx",
    name: "永和县",
    filePath: "yhx",
    registered: false,
  },
  隰县: {
    key: "lx",
    name: "隰县",
    filePath: "lx",
    registered: false,
  },
  汾西县: {
    key: "fxx",
    name: "汾西县",
    filePath: "fxx",
    registered: false,
  },
  霍州市: {
    key: "hzs",
    name: "霍州市",
    filePath: "hzs",
    registered: false,
  },
  吉县: {
    key: "jx",
    name: "吉县",
    filePath: "jx",
    registered: false,
  },
  安泽县: {
    key: "azx",
    name: "安泽县",
    filePath: "azx",
    registered: false,
  },
  大宁县: {
    key: "dnx",
    name: "大宁县",
    filePath: "dnx",
    registered: false,
  },
  蒲县: {
    key: "px",
    name: "蒲县",
    filePath: "px",
    registered: false,
  },
  洪洞县: {
    key: "hdx",
    name: "洪洞县",
    filePath: "hdx",
    registered: false,
  },
  古县: {
    key: "gx",
    name: "古县",
    filePath: "gx",
    registered: false,
  },
  尧都区: {
    key: "ydq",
    name: "尧都区",
    filePath: "ydq",
    registered: false,
  },
  浮山县: {
    key: "fsx",
    name: "浮山县",
    filePath: "fsx",
    registered: false,
  },
  乡宁县: {
    key: "xnx",
    name: "乡宁县",
    filePath: "xnx",
    registered: false,
  },
  襄汾县: {
    key: "xfx",
    name: "襄汾县",
    filePath: "xfx",
    registered: false,
  },
  曲沃县: {
    key: "qwx",
    name: "曲沃县",
    filePath: "qwx",
    registered: false,
  },
  翼城县: {
    key: "ycx",
    name: "翼城县",
    filePath: "ycx",
    registered: false,
  },
  侯马市: {
    key: "hms",
    name: "侯马市",
    filePath: "hms",
    registered: false,
  },
};
