export default {
  运城: {
    key: "ycs",
    name: "运城",
    filePath: "ycs",
    registered: false,
  },
  河津市: {
    key: "hjs",
    name: "河津市",
    filePath: "hjs",
    registered: false,
  },
  稷山县: {
    key: "jsx",
    name: "稷山县",
    filePath: "jsx",
    registered: false,
  },
  新绛县: {
    key: "xjx",
    name: "新绛县",
    filePath: "xjx",
    registered: false,
  },
  绛县: {
    key: "jx",
    name: "绛县",
    filePath: "jx",
    registered: false,
  },
  万荣县: {
    key: "wrx",
    name: "万荣县",
    filePath: "wrx",
    registered: false,
  },
  闻喜县: {
    key: "wxx",
    name: "闻喜县",
    filePath: "wxx",
    registered: false,
  },
  垣曲县: {
    key: "hqx",
    name: "垣曲县",
    filePath: "hqx",
    registered: false,
  },
  临猗县: {
    key: "lyx",
    name: "临猗县",
    filePath: "lyx",
    registered: false,
  },
  盐湖区: {
    key: "yhq",
    name: "盐湖区",
    filePath: "yhq",
    registered: false,
  },
  夏县: {
    key: "xx",
    name: "夏县",
    filePath: "xx",
    registered: false,
  },
  永济市: {
    key: "yjs",
    name: "永济市",
    filePath: "yjs",
    registered: false,
  },
  平陆县: {
    key: "plx",
    name: "平陆县",
    filePath: "plx",
    registered: false,
  },
  芮城县: {
    key: "bcx",
    name: "芮城县",
    filePath: "bcx",
    registered: false,
  },
};
